trigger: none  # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Payment Service Test Results  # Only reference the variable group here

steps:
- script: |
    echo "Checking for AWS CLI..."
    if command -v aws &> /dev/null; then
      echo "AWS CLI is already installed. Skipping installation."
    else
      echo "AWS CLI not found. Installing..."
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install
    fi
  displayName: 'Check and Install AWS CLI'

- script: |
    echo "Validating AWS credentials and region..."

    if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
      echo "❌ Missing AWS credentials or region. Please check variable group."
      exit 1
    fi

    echo "Configuring AWS CLI..."
    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    aws configure set region "$AWS_REGION"

    if [ -n "$AWS_SESSION_TOKEN" ]; then
      echo "Session token detected. Setting it..."
      aws configure set aws_session_token "$AWS_SESSION_TOKEN"
    fi
  displayName: 'Configure AWS CLI'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_REGION: $(AWS_REGION)
    AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)  # Optional

- script: |
    echo "Finding file in S3 matching mask..."
    FILE=$(aws s3 ls $S3_PREFIX --recursive | awk '{print $4}' | grep "$FILE_MASK" | head -n 1)

    if [ -z "$FILE" ]; then
      echo "No file found matching mask: $FILE_MASK"
      exit 1
    fi

    echo "Downloading $FILE from S3..."
    aws s3 cp s3://$S3_BUCKET/$FILE $RENAMED_FILE
  displayName: 'Download and rename file from S3'
  env
