
trigger: none  # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AWSSecrets  # Only reference the variable group here

steps:
- script: |
    echo "Installing AWS CLI..."
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  displayName: 'Install AWS CLI'

- script: |
    echo "Configuring AWS CLI..."
    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    aws configure set region $AWS_REGION

    echo "Finding file in S3 matching mask..."
    FILE=$(aws s3 ls $S3_PREFIX --recursive | awk '{print $4}' | grep "$FILE_MASK" | head -n 1)

    if [ -z "$FILE" ]; then
      echo "No file found matching mask: $FILE_MASK"
      exit 1
    fi

    echo "Downloading $FILE from S3..."
    aws s3 cp s3://$S3_BUCKET/$FILE $RENAMED_FILE
  displayName: 'Download and rename file from S3'
  env:
    S3_BUCKET: testoutput
    S3_PREFIX: s3://778173892410-pipeline-artifacts/[pipeline-cache]/porch/execution/testoutput/
    FILE_MASK: "*accept*.trx"
    RENAMED_FILE: POrch-Test-Results-ACCEPT.trx

- script: |
    echo "Cloning GitHub repo..."
    git config --global user.name "Azure DevOps Bot"
    git config --global user.email "ado-bot@example.com"
    git clone https://$GITHUB_TOKEN@github.com/jlovie02/Service_Test_Results_ACCEPT_INTEGRATE.git repo
    cp $RENAMED_FILE repo/
    cd repo
    git add .
    git commit -m "Add renamed file from S3"
    git push origin main
  displayName: 'Push file to GitHub'
  env:
    RENAMED_FILE: POrch-Test-Results-ACCEPT.trx
