# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# ACCEPT region automation test results
- task: PublishTestResults@2
  displayName: 'Publish Test Results PORCH-accept.trx'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'POrch-accept*.trx'
    testRunTitle: 'POrch Test Results from accept region'
